<program>     ::= <element>+
<element>     ::= <definition> | <expression>

<definition>  ::= ( define <identifier> <expression> )

<expression>  ::= ( <expression> <expression>+ )
			    | <identifier>
			    | <value>

<value>       ::= ( lambda ( <identifier>+ ) <expression> )
                | <integer>
			    | <float>
			    | <boolean>
			    | <string>
